# Generated by Django 5.1 on 2024-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='categoria',
            field=models.TextField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
